### ISSUE TITLE
Unreliable results when using run_passive

### ISSUE THREAD

**Issue by tkorstanje** [binh-bk/SDS011#3]
Dear Binh,

I've been using your script for a single SDS011 finedust sensor on a Raspberry Pi, but I'm having some difficulties using the run_passive mode. When running the script using run_passive, I get proper results returned in the first run, but subsequent queries give 0.0 for both PM2.5 and PM10. When using run_query, I always get a proper result. Interestingly, when I use run_query, the fan DOES stop and start at the given intervals, while, if I understand things correctly, this shouldn't be the case.
When attaching the SDS011 to a Windows computer and querying the working modes, it seems that the SDS011 remembers the last set modes, so I have the feeling that something in the run_passive part is not correctly set?

Can you help me along to a solution?

**Comment by tkorstanje** [comment]
OK, I've been exploring this a bit more, and suddenly I had a brainwave...I set the working period to 1 minute (on my Windows computer), instead of the factory setting of 0 (continuous), and this setting is **retained** at power off. Resetting it to 0 made the run_passive work like a charm again! So as a tip to improve your script: maybe query the working period once before calling run_passive, and when not set to 0, set it to 0 first before continuing.

**Comment by bi2air** [comment]
Thank tkostanje for the comment (and the code). 

Setting run_passive is risky.  I encountered this before.  It happened when the fan was off, and SDS011 did not process the command to kick off fan ON again. It is sure annoying.

It is a good idea to add "watchdog" step and change the operation mode if the PM2.5 readings look not normal.

-Binh
